aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  deploy-website:
    working_directory: ~/docs
    docker:
      - image: circleci/node:8.9.4
    environment:
      USE_SSH: true
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "circleci@users.noreply.github.com"
            git config --global user.name "CircleCI"
            cd website
            yarn install
            yarn run lint
            yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master
