aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2
jobs:
  deploy-website:
    working_directory: ~/website
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "$GITHUB_USERNAME@users.noreply.github.com"
            git config --global user.name "<YOUR_NAME>"
            echo "machine github.com login $GITHUB_USERNAME password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && yarn run lint && GIT_USER=$GITHUB_USERNAME yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-master
